services:
  - type: web
    name: nutrilens-api  # You can change this name if you like
    env: python
    plan: free
    # rootDir: backend # No need for rootDir if this repo ONLY contains backend code
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: '3.11' # Make sure this matches your Python version
      - key: GROQ_API_KEY
        sync: false # Set this manually in Render's UI later
      - key: GROQ_MODEL_NAME
        value: llama-3.1-8b-instant # Or your preferred model
    nativeEnvironment: # Install Tesseract
      packages:
        - key: apt
          name: tesseract-ocr